<?php

namespace app\controllers;

use app\models\Unit;
use app\models\Verifikasi;
use kartik\mpdf\Pdf;
use Yii;
use app\models\Report;
use app\models\search\Report as ReportSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AdminReportController implements the CRUD actions for Report model.
 */
class AdminReportController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Report models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReportSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Report model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        // cek di report apakah sudah ada verifikasi?
        // jika blm maka create baru jika sudah maka tampilkan data saja
        $model = $this->findModel($id);
        if($model->verifikasi){
            $modelVerif = Verifikasi::findOne($model->id_verifikasi);
        }
        else{
            $modelVerif = new Verifikasi(['idReport' => $id]);
        }

        if ($modelVerif->load(Yii::$app->request->post()) && $modelVerif->save()) {
            return $this->redirect(['view', 'id' => $id]);
        }

        return $this->render('view', [
            'model' => $model,
            'modelVerif' => $modelVerif
        ]);
    }

    public function actionPrint($id){
        //Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        /*echo Yii::getAlias('@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',);
        exit;*/
        $model = $this->findModel($id);
        if($model->verifikasi){
            $modelVerif = Verifikasi::findOne($model->id_verifikasi);
        }
        else{
            $modelVerif = new Verifikasi(['idReport' => $id]);
        }

        /*$content =  $this->render('view', [
            'model' => $model,
            'modelVerif' => $modelVerif
        ]);*/

        $content = $this->renderPartial('view', [
            'model' => $model,
            'modelVerif' => $modelVerif
        ]);

        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_FOLIO,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            //'cssFile' => '@bower/bootstrap/dist/css/bootstrap.css',
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            //'cssInline' => '.kv-heading-1{font-size:18px}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
            // call mPDF methods on the fly
            'methods' => [
                'SetHeader'=>['Krajee Report Header'],
                'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }

    /**
     * Creates a new Report model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Report();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Report model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if($model->updated_by != null){
            Yii::$app->session->setFlash('error', 'update pelaporan hanya dilakukan 1x, hubungi komite PMKP');
            return $this->redirect(['index']);
        }

        if (Yii::$app->request->isPost) {
            $send = Yii::$app->db->createCommand()->update('report', [
                'biaya' => Yii::$app->request->post('biaya'),
                'umur' => Yii::$app->request->post('umur'),
                'jk' => Yii::$app->request->post('jk'),
                'id_jenis' => Yii::$app->request->post('id_jenis'),
                'updated_date' => date('Y-m-d H:i:s'),
                'updated_by' => Yii::$app->user->id,
                'id_band' => Yii::$app->request->post('id_band'),
                'pelapor_pertama' => Yii::$app->request->post('pelapor_pertama'),
                'menyangkut_pasien' => Yii::$app->request->post('menyangkut_pasien'),
                'penyakit' => Yii::$app->request->post('penyakit'),
                'unit_penyebab' => Yii::$app->request->post('unit_penyebab'),
                'akibat' => Yii::$app->request->post('akibat'),
                'respon_insiden' => Yii::$app->request->post('respon_insiden'),
                'tim' => Yii::$app->request->post('tim'),
                'pernah_terjadi' => Yii::$app->request->post('pernah_terjadi'),
                'no1_1' => Yii::$app->request->post('1_1'),
                'no1_2' => Yii::$app->request->post('1_2'),
                'no1_3' => Yii::$app->request->post('1_3'),
                'no1_4' => Yii::$app->request->post('1_4'),
                'no1_5' => Yii::$app->request->post('1_5'),
                'no2_1' => Yii::$app->request->post('2_1'),
                'no2_2' => Yii::$app->request->post('2_2'),
                'no2_3' => Yii::$app->request->post('2_3'),
                'no2_4' => Yii::$app->request->post('2_4'),
                'no2_5' => Yii::$app->request->post('2_5'),
                'no2_6' => Yii::$app->request->post('2_6'),
                'no2_7' => Yii::$app->request->post('2_7'),
                'no3_1' => Yii::$app->request->post('3_1'),
                'no3_2' => Yii::$app->request->post('3_2'),
                'no3_3' => Yii::$app->request->post('3_3'),
                'no3_4' => Yii::$app->request->post('3_4'),
                'no3_5' => Yii::$app->request->post('3_5'),
                'no3_6' => Yii::$app->request->post('3_6'),
                'no3_7' => Yii::$app->request->post('3_7'),
                'no3_8' => Yii::$app->request->post('3_8'),
                'no3_9' => Yii::$app->request->post('3_9'),
                'no4_1' => Yii::$app->request->post('4_1'),
                'no4_2' => Yii::$app->request->post('4_2'),
                'no4_3' => Yii::$app->request->post('4_3'),
                'no4_4' => Yii::$app->request->post('4_4'),
                'no4_5' => Yii::$app->request->post('4_5'),
                'no4_6' => Yii::$app->request->post('4_6'),
                'no4_7' => Yii::$app->request->post('4_7'),
                'no4_8' => Yii::$app->request->post('4_8'),
                'no4_9' => Yii::$app->request->post('4_9'),
                'no4_10' => Yii::$app->request->post('4_10'),
                'no5_1' => Yii::$app->request->post('5_1'),
                'no5_2' => Yii::$app->request->post('5_2'),
                'no5_3' => Yii::$app->request->post('5_3'),
                'no5_4' => Yii::$app->request->post('5_4'),
                'no5_5' => Yii::$app->request->post('5_5'),
                'no5_6' => Yii::$app->request->post('5_6'),
                'no5_7' => Yii::$app->request->post('5_7'),
                'no5_8' => Yii::$app->request->post('5_8'),
                'no5_9' => Yii::$app->request->post('5_9'),
                'no6_1' => Yii::$app->request->post('6_1'),
                'no6_2' => Yii::$app->request->post('6_2'),
                'no6_3' => Yii::$app->request->post('6_3'),
                'no6_4' => Yii::$app->request->post('6_4'),
                'no6_5' => Yii::$app->request->post('6_5'),
                'no6_6' => Yii::$app->request->post('6_6'),
                'no6_7' => Yii::$app->request->post('6_7'),
                'no6_8' => Yii::$app->request->post('6_8'),
                'no6_9' => Yii::$app->request->post('6_9'),
                'no6_10' => Yii::$app->request->post('6_10'),
                'no6_11' => Yii::$app->request->post('6_11'),
                'no7_1' => Yii::$app->request->post('7_1'),
                'no7_2' => Yii::$app->request->post('7_2'),
                'no7_3' => Yii::$app->request->post('7_3'),
                'no7_4' => Yii::$app->request->post('7_4'),
                'no7_5' => Yii::$app->request->post('7_5'),
                'no7_6' => Yii::$app->request->post('7_6'),
                'no8_1' => Yii::$app->request->post('8_1'),
                'no8_2' => Yii::$app->request->post('8_2'),
                'no8_3' => Yii::$app->request->post('8_3'),
                'no8_4' => Yii::$app->request->post('8_4'),
                'no8_5' => Yii::$app->request->post('8_5'),
                'no8_6' => Yii::$app->request->post('8_6'),
                'no8_7' => Yii::$app->request->post('8_7'),
                'no9_1' => Yii::$app->request->post('9_1'),
            ],['id' => Yii::$app->request->get('id')])->execute();
            if($send){
                Yii::$app->session->setFlash('success','Berhasil Simpan Perubahan');
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else{
                Yii::$app->session->setFlash('error','Gagal Simpan Perubahan');
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Report model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Report model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Report the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Report::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
