<?php

namespace app\controllers;

use app\models\Unit;
use Yii;
use GuzzleHttp\Client;

class ReportController extends \yii\web\Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }

    public function actionIndex()
    {
        if(Yii::$app->request->isPost){
            /*echo "<pre>";
            print_r(Yii::$app->request->post());
            exit;*/
            $send = Yii::$app->db->createCommand()->insert('report', [
                'pelapor' => Yii::$app->request->post('pelapor'),
                'norm' => Yii::$app->request->post('norm'),
                'biaya' => Yii::$app->request->post('biaya'),
                'umur' => Yii::$app->request->post('umur'),
                'jk' => Yii::$app->request->post('jk'),
                'tanggal' => Yii::$app->request->post('tgl'),
                'id_jenis' => Yii::$app->request->post('id_jenis'),
                'id_unit' => Yii::$app->request->post('id_unit'),
                'created_date' => date('Y-m-d H:i:s'),
                'id_band' => Yii::$app->request->post('id_band'),
                'kronologi' => Yii::$app->request->post('kronologi'),
                'pelapor_pertama' => Yii::$app->request->post('pelapor_pertama'),
                'menyangkut_pasien' => Yii::$app->request->post('menyangkut_pasien'),
                'penyakit' => Yii::$app->request->post('penyakit'),
                'unit_penyebab' => Yii::$app->request->post('unit_penyebab'),
                'akibat' => Yii::$app->request->post('akibat'),
                'respon_insiden' => Yii::$app->request->post('respon_insiden'),
                'tim' => Yii::$app->request->post('tim'),
                'pernah_terjadi' => Yii::$app->request->post('pernah_terjadi'),
                'no1_1' => Yii::$app->request->post('1_1'),
                'no1_2' => Yii::$app->request->post('1_2'),
                'no1_3' => Yii::$app->request->post('1_3'),
                'no1_4' => Yii::$app->request->post('1_4'),
                'no1_5' => Yii::$app->request->post('1_5'),
                'no2_1' => Yii::$app->request->post('2_1'),
                'no2_2' => Yii::$app->request->post('2_2'),
                'no2_3' => Yii::$app->request->post('2_3'),
                'no2_4' => Yii::$app->request->post('2_4'),
                'no2_5' => Yii::$app->request->post('2_5'),
                'no2_6' => Yii::$app->request->post('2_6'),
                'no2_7' => Yii::$app->request->post('2_7'),
                'no3_1' => Yii::$app->request->post('3_1'),
                'no3_2' => Yii::$app->request->post('3_2'),
                'no3_3' => Yii::$app->request->post('3_3'),
                'no3_4' => Yii::$app->request->post('3_4'),
                'no3_5' => Yii::$app->request->post('3_5'),
                'no3_6' => Yii::$app->request->post('3_6'),
                'no3_7' => Yii::$app->request->post('3_7'),
                'no3_8' => Yii::$app->request->post('3_8'),
                'no3_9' => Yii::$app->request->post('3_9'),
                'no4_1' => Yii::$app->request->post('4_1'),
                'no4_2' => Yii::$app->request->post('4_2'),
                'no4_3' => Yii::$app->request->post('4_3'),
                'no4_4' => Yii::$app->request->post('4_4'),
                'no4_5' => Yii::$app->request->post('4_5'),
                'no4_6' => Yii::$app->request->post('4_6'),
                'no4_7' => Yii::$app->request->post('4_7'),
                'no4_8' => Yii::$app->request->post('4_8'),
                'no4_9' => Yii::$app->request->post('4_9'),
                'no4_10' => Yii::$app->request->post('4_10'),
                'no5_1' => Yii::$app->request->post('5_1'),
                'no5_2' => Yii::$app->request->post('5_2'),
                'no5_3' => Yii::$app->request->post('5_3'),
                'no5_4' => Yii::$app->request->post('5_4'),
                'no5_5' => Yii::$app->request->post('5_5'),
                'no5_6' => Yii::$app->request->post('5_6'),
                'no5_7' => Yii::$app->request->post('5_7'),
                'no5_8' => Yii::$app->request->post('5_8'),
                'no5_9' => Yii::$app->request->post('5_9'),
                'no6_1' => Yii::$app->request->post('6_1'),
                'no6_2' => Yii::$app->request->post('6_2'),
                'no6_3' => Yii::$app->request->post('6_3'),
                'no6_4' => Yii::$app->request->post('6_4'),
                'no6_5' => Yii::$app->request->post('6_5'),
                'no6_6' => Yii::$app->request->post('6_6'),
                'no6_7' => Yii::$app->request->post('6_7'),
                'no6_8' => Yii::$app->request->post('6_8'),
                'no6_9' => Yii::$app->request->post('6_9'),
                'no6_10' => Yii::$app->request->post('6_10'),
                'no6_11' => Yii::$app->request->post('6_11'),
                'no7_1' => Yii::$app->request->post('7_1'),
                'no7_2' => Yii::$app->request->post('7_2'),
                'no7_3' => Yii::$app->request->post('7_3'),
                'no7_4' => Yii::$app->request->post('7_4'),
                'no7_5' => Yii::$app->request->post('7_5'),
                'no7_6' => Yii::$app->request->post('7_6'),
                'no8_1' => Yii::$app->request->post('8_1'),
                'no8_2' => Yii::$app->request->post('8_2'),
                'no8_3' => Yii::$app->request->post('8_3'),
                'no8_4' => Yii::$app->request->post('8_4'),
                'no8_5' => Yii::$app->request->post('8_5'),
                'no8_6' => Yii::$app->request->post('8_6'),
                'no8_7' => Yii::$app->request->post('8_7'),
                'no9_1' => Yii::$app->request->post('9_1'),
            ])->execute();
            if($send){
                Yii::$app->session->setFlash('success','Laporan Berhasil Terkirim');
                    // send WA ke user kepala dan user pmkp
                    // kirim notifikasi ke WA tim IKP
                    /*foreach (Yii::$app->params['timIkp'] as $wa){
                        $client = new Client([
							'headers' => [
								'Content-Type' => 'application/json',
								'Accept' => 'application/json',
							],
						]);
                        $client->request('POST', 'http://10.99.2.254:3000/send-message',
                            [
                                'json' => [
                                    'to' => $wa,
                                    'message' => 'Ada Laporan Insiden Keselamatan pasien Baru, Segera cek aplikasi insiden'
                                ]
                            ]
                        );
                    }*/	

                    // kirim notifikasi ke kepala ruang / instalasi, tunggu konfirmasi dari dr tari
                    // $waUnit = Yii::$app->db
                    // ->createCommand('
                    //     select c.nomerWa 
                    //     from user_unit a 
                    //     left join user b on b.id = a.id_user
                    //     left join user_attribut c on c.idUser = b.id
                    //     where a.id_unit = :id_unit and a.publish = 1 AND c.`nomerWa` IS NOT NULL
                    //     ')
                    // ->bindValue(':id_unit',Yii::$app->request->post('id_unit'))
                    // ->queryColumn();                    

                    // if($waUnit){
                    //     $namaUnit = Unit::getUnitName(Yii::$app->request->post('id_unit'));
                    //     foreach ($waUnit as $nomer) {
                    //         $client = new Client();
                    //         $client->request('POST', 'http://194.169.46.193:8000/send-message',
                    //             [
                    //                 'form_params' => [
                    //                     'number' => $nomer,
                    //                     'message' => 'Ada Laporan Insiden Keselamatan pasien di Unit '.$namaUnit.', Segera cek aplikasi insiden'
                    //                 ]
                    //             ]
                    //         );
                    //     }
                    // }
            }
            else{
                Yii::$app->session->setFlash('error','Laporan Gagal Terkirim');
            }

            return $this->redirect(['report/index']);
        }
        return $this->render('index');
    }

}
