<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "k3rsjenis".
 *
 * @property int $id
 * @property string $nama
 * @property int $publish
 * @property int|null $createdBy
 * @property string|null $createdDate
 * @property int|null $modifiedBy
 * @property string|null $modifiedDate
 *
 * @property K3rslap[] $k3rslaps
 */
class K3rsjenis extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'k3rsjenis';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['publish', 'createdBy', 'modifiedBy'], 'integer'],
            [['createdDate', 'modifiedDate'], 'safe'],
            [['nama'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Jenis Insiden',
            'publish' => 'Publish',
            'createdBy' => 'Created By',
            'createdDate' => 'Created Date',
            'modifiedBy' => 'Modified By',
            'modifiedDate' => 'Modified Date',
        ];
    }

    public static function getJeniss($id=null){
        $list = ArrayHelper::map(
            self::find()->where(['publish' => 1])->all()
            ,'id','nama');
        if($id == null){
            return $list;
        }
        return $list[$id];
    }

    /**
     * Gets query for [[K3rslaps]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLaporan()
    {
        return $this->hasMany(K3rslap::className(), ['jenisInsiden' => 'id']);
    }

    public function getCreated()
    {
        return $this->hasOne(Users::className(), ['id' => 'createdBy']);
    }

    public function getModified()
    {
        return $this->hasOne(Users::className(), ['id' => 'modifiedBy']);
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->createdBy = Yii::$app->user->id;
            $this->createdDate = date('Y-m-d H:i:s');
        }
        else{
            $this->modifiedBy = Yii::$app->user->id;
            $this->modifiedDate = date('Y-m-d H:i:s');
        }
        return true;
    }
}
