<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "k3rslap".
 *
 * @property int $id
 * @property string $namaTerlapor
 * @property int $unitTerlapor
 * @property string $tglJamKejadian
 * @property int $jenisInsiden
 * @property string $kronologis
 * @property string $tindakanKejadian
 * @property string $penerimaLaporan
 * @property string $tglPenerima
 * @property int $publish 1:publish;2:unpublish
 * @property int $createdBy
 * @property string $createdDate
 * @property int|null $modifiedBy
 * @property string|null $modifiedDate
 *
 * @property Unit $unitTerlapor0
 * @property K3rsjenis $jenisInsiden0
 */
class K3rslap extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'k3rslap';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['namaTerlapor', 'unitTerlapor', 'tglJamKejadian', 'jenisInsiden', 'kronologis', 'tindakanKejadian', 'createdBy', 'createdDate'], 'required'],
            [['unitTerlapor', 'jenisInsiden', 'penerimaLaporan', 'publish', 'modifiedBy'], 'integer'],
            [['tglJamKejadian', 'tglPenerima', 'createdDate', 'modifiedDate'], 'safe'],
            [['kronologis', 'tindakanKejadian'], 'string'],
            [['namaTerlapor', 'createdBy'], 'string', 'max' => 150],
            [['unitTerlapor'], 'exist', 'skipOnError' => true, 'targetClass' => Unit::className(), 'targetAttribute' => ['unitTerlapor' => 'id']],
            [['jenisInsiden'], 'exist', 'skipOnError' => true, 'targetClass' => K3rsjenis::className(), 'targetAttribute' => ['jenisInsiden' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'namaTerlapor' => 'Nama Terlapor',
            'unitTerlapor' => 'Unit Terlapor',
            'tglJamKejadian' => 'Tanggal Jam Kejadian',
            'jenisInsiden' => 'Jenis Insiden',
            'kronologis' => 'Kronologis Insiden',
            'tindakanKejadian' => 'Tindakan Setelah Kejadian',
            'penerimaLaporan' => 'Penerima Laporan',
            'tglPenerima' => 'Tanggal Menerima Laporan',
            'publish' => 'Publish',
            'createdBy' => 'Pembuat Laporan',
            'createdDate' => 'Created Date',
            'modifiedBy' => 'Modified By',
            'modifiedDate' => 'Modified Date',
        ];
    }

    /**
     * Gets query for [[UnitTerlapor0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUnit()
    {
        return $this->hasOne(Unit::className(), ['id' => 'unitTerlapor']);
    }

    /**
     * Gets query for [[JenisInsiden0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJenis()
    {
        return $this->hasOne(K3rsjenis::className(), ['id' => 'jenisInsiden']);
    }

    public function getPenerima()
    {
        return $this->hasOne(Users::className(), ['id' => 'penerimaLaporan']);
    }

    public function getModified()
    {
        return $this->hasOne(Users::className(), ['id' => 'modifiedBy']);
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if(!$insert){
            $this->modifiedBy = Yii::$app->user->id;
            $this->modifiedDate = date('Y-m-d H:i:s');
        }
        return true;
    }
}
