<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "report_investigasi".
 *
 * @property int $id
 * @property int $id_report
 * @property string $penyebab
 * @property string $akar
 * @property string $rekomendasi
 * @property int|null $publish
 * @property int|null $created_by
 * @property string|null $created_date
 * @property int|null $updated_by
 * @property string|null $updated_date
 *
 * @property Report $report
 */
class ReportInvestigasi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'report_investigasi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_report', 'id_band', 'penyebab', 'akar', 'tindakan', 'rekomendasi'], 'required'],
            [['id_report', 'id_band', 'publish', 'created_by', 'updated_by'], 'integer'],
            [['penyebab', 'akar', 'rekomendasi', 'tindakan'], 'string'],
            [['created_date', 'updated_date'], 'safe'],
            [['id_report'], 'exist', 'skipOnError' => true, 'targetClass' => Report::className(), 'targetAttribute' => ['id_report' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_report' => 'Id Report',
            'id_band' => 'Warna Band',
            'penyebab' => 'Penyebab Langsung (Direct / Proximate / Immediate Cause)',
            'akar' => 'Akar penyebab masalah (underlying - root cause)',
            'rekomendasi' => 'Rekomendasi / Solusi',
            'tindakan' => 'Tindakan Yang Akan Dilakukan',
            'publish' => 'Publish',
            'created_by' => 'Dibuat Oleh',
            'created_date' => 'Dibuat Tanggal',
            'updated_by' => 'DiUbah Oleh',
            'updated_date' => 'DiUbah Tanggal',
        ];
    }

    /**
     * Gets query for [[Report]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getReport()
    {
        return $this->hasOne(Report::className(), ['id' => 'id_report']);
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->created_by = Yii::$app->user->id;
            $this->created_date = date('Y-m-d H:i:s');
        }
        else{
            $this->updated_by = Yii::$app->user->id;
            $this->updated_date = date('Y-m-d H:i:s');
        }
        return true;
    }
}
