<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "unit".
 *
 * @property int $id
 * @property string $nama
 * @property int|null $publish
 * @property int|null $created_by
 * @property string|null $created_date
 * @property int|null $updated_by
 * @property string|null $updated_date
 *
 * @property Report[] $reports
 */
class Unit extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'unit';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['publish', 'created_by', 'updated_by'], 'integer'],
            [['created_date', 'updated_date'], 'safe'],
            [['nama'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'id_kepala' => 'PIC',
            'publish' => 'Publish',
            'created_by' => 'Created By',
            'created_date' => 'Created Date',
            'updated_by' => 'Updated By',
            'updated_date' => 'Updated Date',
        ];
    }

    /**
     * Gets query for [[Reports]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getReports()
    {
        return $this->hasMany(Report::className(), ['id_unit' => 'id']);
    }

    public function getUnitName($id)
    {
        $unit = self::findOne($id);
        return $unit->nama;
    }

    /**
     * Gets query for [[UserUnits]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserUnits()
    {
        return $this->hasMany(UserUnit::className(), ['id_unit' => 'id']);
    }

    public static function getUnits($id=null){
        $listUnit = ArrayHelper::map(
            self::find()->where(['publish' => 1])->all()
                ,'id','nama');
        if($id == null){
            return $listUnit;
        }
        return $listUnit[$id];
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->created_by = Yii::$app->user->id;
            $this->created_date = date('Y-m-d H:i:s');
        }
        else{
            $this->updated_by = Yii::$app->user->id;
            $this->updated_date = date('Y-m-d H:i:s');

        }
        return true;
    }
}
