<?php

namespace app\models;

use Yii;
use yii\web\ForbiddenHttpException;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "user_unit".
 *
 * @property int $id
 * @property int $id_user
 * @property int $id_unit
 * @property int|null $publish
 * @property int|null $created_by
 * @property string|null $created_date
 * @property int|null $updated_by
 * @property string|null $updated_date
 *
 * @property User $user
 * @property Unit $unit
 */
class UserUnit extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_unit';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'id_unit'], 'required'],
            [['id_user', 'id_unit', 'publish', 'created_by', 'updated_by'], 'integer'],
            [['created_date', 'updated_date'], 'safe'],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id']],
            [['id_unit'], 'exist', 'skipOnError' => true, 'targetClass' => Unit::className(), 'targetAttribute' => ['id_unit' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'id_unit' => 'Id Unit',
            'publish' => 'Publish',
            'created_by' => 'Created By',
            'created_date' => 'Created Date',
            'updated_by' => 'Updated By',
            'updated_date' => 'Updated Date',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'id_user']);
    }

    /**
     * Gets query for [[Unit]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUnit()
    {
        return $this->hasOne(Unit::className(), ['id' => 'id_unit']);
    }

    public static function getUnits($id_user)
    {
        $findUserUnit = [];
        $userCek = Yii::$app->db
            ->createCommand("select * from auth_assignment where user_id = :id")
            ->bindValue(':id', Yii::$app->user->id)
            ->queryOne();
        if($userCek){
            $qUserUnit = UserUnit::find();
            if($userCek['item_name'] != 'pmkp'){
                $qUserUnit->where([
                        'id_user' => Yii::$app->user->id,
                        'publish' => 1,
                        ]);
            }
            else{
                $qUserUnit->where([
                    'publish' => 1,
                    ]);
            }
            $data = $qUserUnit->all();

            if(!$data){
                throw new ForbiddenHttpException('User Kamu belum disetting Hak Akses');
            }

            $findUserUnit = ArrayHelper::map($data, 'id_unit','unit.nama');
        }
        else{
            throw new ForbiddenHttpException('Hak Akses belum di setting');
        }
        return $findUserUnit;
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->created_by = Yii::$app->user->id;
            $this->created_date = date('Y-m-d H:i:s');
        }
        else{
            $this->updated_by = Yii::$app->user->id;
            $this->updated_date = date('Y-m-d H:i:s');

        }
        return true;
    }
}
