<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "verifikasi".
 *
 * @property int $id
 * @property int $id_verifikator
 * @property int $id_band 1:biru,2:hijau,3:kuning,4:merah
 * @property int $id_jenis 1:KNC,2:KTC,3:KTD,4:Sentinel,5:Resiko/KPC
 * @property int $aktivasi 1:ya,2:tidak
 * @property int $investigasi 1:InvestigasiSederhanaOlehUnit,2:InvestigasiOlehSubKomiteKeselamatanPasien
 * @property int $tindak_lanjut 1:RCAUnit,2:RCAKomiteMutu
 * @property string $kesimpulan
 * @property int|null $publish 1:publish,2:unpublish
 * @property int|null $created_by
 * @property string|null $created_date
 * @property int|null $updated_by
 * @property string|null $updated_date
 *
 * @property Report[] $reports
 * @property User $verifikator
 */
class Verifikasi extends \yii\db\ActiveRecord
{
    public $idReport;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'verifikasi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_verifikator', 'id_band', 'id_jenis', 'aktivasi', 'investigasi', 'tindak_lanjut', 'kesimpulan'], 'required'],
            [['id_verifikator', 'id_band', 'id_jenis', 'aktivasi', 'investigasi', 'tindak_lanjut', 'publish', 'created_by', 'updated_by'], 'integer'],
            [['kesimpulan'], 'string'],
            [['created_date', 'updated_date', 'idReport'], 'safe'],
            [['id_verifikator'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_verifikator' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_verifikator' => 'Nama Verifikator',
            'id_band' => 'Band Warna',
            'id_jenis' => 'Jenis Insiden',
            'aktivasi' => 'Aktivasi',
            'investigasi' => 'Investigasi',
            'tindak_lanjut' => 'Tindak Lanjut',
            'kesimpulan' => 'Kesimpulan',
            'publish' => 'Publish',
            'created_by' => 'Created By',
            'created_date' => 'Created Date',
            'updated_by' => 'Updated By',
            'updated_date' => 'Updated Date',
        ];
    }
    // aktivasi 1:ya,2:tidak
    // investigasi 1:InvestigasiSederhanaOlehUnit,2:InvestigasiOlehSubKomiteKeselamatanPasien
    // tindak lanjut 1:RCAUnit,2:RCAKomiteMutu

    public static function getStatAktivasi($id=null){
        $listAktivasi = [
            1 => 'Ya',
            2 => 'Tidak'
        ];
        if($id == null){
            return $listAktivasi;
        }
        return $listAktivasi[$id];
    }

    public static function getStatInvestigasi($id=null){
        $listInvestigasi = [
            1 => 'Investigasi Sederhana Oleh Unit',
            2 => 'Investigasi Oleh Sub Komite Keselamatan Pasien'
        ];
        if($id == null){
            return $listInvestigasi;
        }
        return $listInvestigasi[$id];
    }

    public static function getStatTindak($id=null){
        $listTindak = [
            1 => 'RCA Unit',
            2 => 'RCA Komite Mutu'
        ];
        if($id == null){
            return $listTindak;
        }
        return $listTindak[$id];
    }

    /**
     * Gets query for [[Reports]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getReports()
    {
        return $this->hasMany(Report::className(), ['id_verifikasi' => 'id']);
    }

    /**
     * Gets query for [[Verifikator]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVerifikator()
    {
        return $this->hasOne(Users::className(), ['id' => 'id_verifikator']);
    }

    public function beforeValidate()
    {
        parent::beforeValidate(); // TODO: Change the autogenerated stub
        $this->id_verifikator = Yii::$app->user->id;
        return true;
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->created_by = Yii::$app->user->id;
            $this->created_date = date('Y-m-d H:i:s');
        }
        else{
            $this->updated_by = Yii::$app->user->id;
            $this->updated_date = date('Y-m-d H:i:s');

        }
        return true;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if($insert){
            $modelReport = Report::findOne($this->idReport);
            $modelReport->id_verifikasi = $this->id;
            $modelReport->save(false);
        }
    }
}
